// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Presby struct {
	Key       string   `json:"key"`
	ID        int      `json:"id"`
	IsActive  bool     `json:"isActive"`
	Last      string   `json:"last"`
	Guests    []string `json:"guests"`
	Guestings []string `json:"guestings"`
	Hostings  []string `json:"hostings"`
	Seats     int      `json:"seats"`
	Unknown1  int      `json:"unknown1"`
	Unknown2  int      `json:"unknown2"`
	Email     string   `json:"email"`
	Home      string   `json:"home"`
	Cell      string   `json:"cell"`
	Smail     string   `json:"smail"`
	City      string   `json:"city"`
	St        string   `json:"st"`
	Zip       string   `json:"zip"`
	Mmail     string   `json:"mmail"`
}
